### ISSUE TITLE
Crash when ending conversation

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#109]
This is related with #57 , but not the same. Even when Alice ends her conversation but Bob does not, eventually the plugin crashes (even when Bob does no action)

**Comment by peterpalau** [comment]
I realize that this happens mainly when you are using the [`prekey-server-docker-compose`](https://github.com/otrv4/prekey-server-docker-compose), maybe because of the issues with the [permissions](https://github.com/otrv4/prekey-server-docker-compose#troubleshoots) or something else.

I recently used some accounts from the `jabber.otr.im` server and this does not happen.

**Comment by peterpalau** [comment]
This is one of error that appears when `Alice` request private conversation with `Bob`:

```
pidgin: client.c:826: otrng_client_get_client_profile: Assertion `client->client_profile != NULL' failed.
Aborted (core dumped)
```

**Comment by claucece** [comment]
Ohh! @peterpalau ... can we pair tomorrow to check this?

**Comment by peterpalau** [comment]
@claucece of course we can

**Comment by MauroVelasco** [comment]
Hi @claucece, I notice this line: `conv->conn` as the culprit ;), looks like `conn` contains an invalid memory address. This is invoked in (libotr-ng/client.c):

` expiration_time = get_session_expiry_time_from(conv->conn);`

I added a validation in order to avoid this behavior:

`if( conv!=NULL && conv->conn!=NULL ){

        expiration_time = get_session_expiry_time_from(conv->conn);

        if (conv->conn->keys->last_generated < now - expiration_time) {

          otrng_client_expire_session(conv);

        }

    }`

Although conv->conn is still producing the segmentation fault.

**Comment by claucece** [comment]
Thanks @MauroVelasco !

What I did to fix it is:

```
  for (el = client->conversations; el; el = el->next) {
    if (!conv) {
      return;
    }
      conv = el->data;
    expiration_time = get_session_expiry_time_from(conv->conn);
    if (conv->conn->keys->last_generated < now - expiration_time) {
      otrng_client_expire_session(conv);
    }
  }
```

**Comment by MauroVelasco** [comment]
Hi @claucece , this, Did you uploaded, to test it?

**Comment by MauroVelasco** [comment]
Hi @claucece, I did the modification in client.c and testing.

**Comment by claucece** [comment]
@MauroVelasco No, I did not upload hahaha.. Did you test it? Did it work?

**Comment by MauroVelasco** [comment]
Hi @claucece, yes I did the change as suggested, don't have the issue until now, let you know if the issue comes again.

**Comment by claucece** [comment]
woo!!! awesome! @MauroVelasco .. should we close it?

**Comment by MauroVelasco** [comment]
Hi @claucece, I think so, I was unable to replicate the issue after the modification.

**Comment by claucece** [comment]
Awesome! Closing it! <3

**Comment by claucece** [comment]
I did not realized that the change is not pushed ahhaha.. want to push @MauroVelasco ?

**Comment by MauroVelasco** [comment]
hi @claucece, yeah, sure I'll in minutes

**Comment by MauroVelasco** [comment]
Hi @claucece, it's uploaded
