### ISSUE TITLE
Package 'libffi', required by 'gobject-2.0', not found MACOS-10.12.6 Sierra

### ISSUE THREAD

**Issue by shiv1m** [otrv4/pidgin-otrng#113]
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
gyp: Call to 'pkg-config cairo --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:348:16)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 16.7.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Already tried export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig"
Using node 12.7.0

Still it is not working?
Any clues?

**Comment by claucece** [comment]
Hey!

Is this related to this library, meaning to pidgin-otrng? Cause from your stack, it seems you are referring to some node application, exacty (`node-pre-gyp`). Perhaps, open your issue on the correct repo, meaning https://github.com/mapbox/node-pre-gyp ?

That said, this can be due to different things. `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/` should work but it depends on how your path is set, if it was installed using brew, etc. If you want to talk about this, reach me over twitter at '@claucece'. 

I will close this in this library as it is not related to it.
