### ISSUE TITLE
Crash at start 

### ISSUE THREAD

**Issue by claucece** [otrv4/pidgin-otrng#76]
Due to some recent additions (apparently because of orchestration), pidgin will crash when there is previously no persisted files. 

```
(22:58:25) jabber: jabber_actions: have pep: YES
otrng_client_ensure_correct_state()
orchestration.load_long_term_keys_from_storage
orchestration.create_long_term_keys
(22:58:26) dnssrv: res_query returned an error
(22:58:26) jabber: got 0 SRV responses for STUN.
orchestration.create_long_term_keys
Pidgin 2.12.0 has segfaulted and attempted to dump a core file.
```

**Comment by claucece** [comment]
cc./ @olabini @giovaneliberato

**Comment by olabini** [comment]
OK, so I have now fixed this with the current version of libotr-ng and pidgin-otrng. However, in order to fix it I had to comment out a line that read `otrng_prekey_client_set_client_profile_publication(client->prekey_client)` inside of `profiles_create_client_profile`, since there is no guarantee a prekey_client will exist at the time this function is called. @giovaneliberato - we need to retain the other methods for publishing client profiles and other things until the new functionality works.
